# development environment for mff
# to install use
# conda env create --file environment-dev.yml
# activate the env with:
# conda activate mff-dev
name: mff-dev
channels:
- conda-forge
- nodefaults
dependencies:
- python=3.11.7
- pandas=2.2.0
- numpy=1.26.3
- scipy=1.12.0
- dask=2024.1.1
- scikit-learn=1.4.0
- pytest=8.0.0
- black=24.1.0
- ruff=0.1.14
- pip=23.3.2